package com.nt.test;
// Generated Apr 10, 2019 3:25:32 PM by Hibernate Tools 5.4.2.Final

/**
 * Phno generated by hbm2java
 */
public class Phno implements java.io.Serializable {

	private PhnoId id;
	private Person person;

	public Phno() {
	}

	public Phno(PhnoId id) {
		this.id = id;
	}

	public Phno(PhnoId id, Person person) {
		this.id = id;
		this.person = person;
	}

	public PhnoId getId() {
		return this.id;
	}

	public void setId(PhnoId id) {
		this.id = id;
	}

	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

}
