package com.nt.domain;
// Generated Apr 12, 2019 11:25:49 AM by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PhoneNumber generated by hbm2java
 */
@Entity
@Table(name = "PHONE_NUMBER", schema = "SCOTT")
public class PhoneNumber implements java.io.Serializable {

	private long phone;
	private UserTable userTable;
	private String numberType;

	public PhoneNumber() {
	}

	public PhoneNumber(long phone) {
		this.phone = phone;
	}

	public PhoneNumber(long phone, UserTable userTable, String numberType) {
		this.phone = phone;
		this.userTable = userTable;
		this.numberType = numberType;
	}

	@Id

	@Column(name = "PHONE", unique = true, nullable = false, precision = 10, scale = 0)
	public long getPhone() {
		return this.phone;
	}

	public void setPhone(long phone) {
		this.phone = phone;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "UNID")
	public UserTable getUserTable() {
		return this.userTable;
	}

	public void setUserTable(UserTable userTable) {
		this.userTable = userTable;
	}

	@Column(name = "NUMBER_TYPE", length = 10)
	public String getNumberType() {
		return this.numberType;
	}

	public void setNumberType(String numberType) {
		this.numberType = numberType;
	}

}
