package com.nt.domain;
// Generated Apr 12, 2019 11:25:49 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UserTable generated by hbm2java
 */
@Entity
@Table(name = "USER_TABLE", schema = "SCOTT")
public class UserTable implements java.io.Serializable {

	private long userId;
	private String firstName;
	private Set<PhoneNumber> phoneNumbers = new HashSet<PhoneNumber>(0);

	public UserTable() {
	}

	public UserTable(long userId) {
		this.userId = userId;
	}

	public UserTable(long userId, String firstName, Set<PhoneNumber> phoneNumbers) {
		this.userId = userId;
		this.firstName = firstName;
		this.phoneNumbers = phoneNumbers;
	}

	@Id

	@Column(name = "USER_ID", unique = true, nullable = false, precision = 10, scale = 0)
	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	@Column(name = "FIRST_NAME", length = 10)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "userTable")
	public Set<PhoneNumber> getPhoneNumbers() {
		return this.phoneNumbers;
	}

	public void setPhoneNumbers(Set<PhoneNumber> phoneNumbers) {
		this.phoneNumbers = phoneNumbers;
	}

}
