package com.nt.test;
// Generated Apr 10, 2019 3:25:32 PM by Hibernate Tools 5.4.2.Final

/**
 * PhnoId generated by hbm2java
 */
public class PhnoId implements java.io.Serializable {

	private Long ph1;
	private Long ph2;
	private Long no;

	public PhnoId() {
	}

	public PhnoId(Long ph1, Long ph2, Long no) {
		this.ph1 = ph1;
		this.ph2 = ph2;
		this.no = no;
	}

	public Long getPh1() {
		return this.ph1;
	}

	public void setPh1(Long ph1) {
		this.ph1 = ph1;
	}

	public Long getPh2() {
		return this.ph2;
	}

	public void setPh2(Long ph2) {
		this.ph2 = ph2;
	}

	public Long getNo() {
		return this.no;
	}

	public void setNo(Long no) {
		this.no = no;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PhnoId))
			return false;
		PhnoId castOther = (PhnoId) other;

		return ((this.getPh1() == castOther.getPh1())
				|| (this.getPh1() != null && castOther.getPh1() != null && this.getPh1().equals(castOther.getPh1())))
				&& ((this.getPh2() == castOther.getPh2()) || (this.getPh2() != null && castOther.getPh2() != null
						&& this.getPh2().equals(castOther.getPh2())))
				&& ((this.getNo() == castOther.getNo()) || (this.getNo() != null && castOther.getNo() != null
						&& this.getNo().equals(castOther.getNo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getPh1() == null ? 0 : this.getPh1().hashCode());
		result = 37 * result + (getPh2() == null ? 0 : this.getPh2().hashCode());
		result = 37 * result + (getNo() == null ? 0 : this.getNo().hashCode());
		return result;
	}

}
