package com.nt.domain;
// Generated Apr 11, 2019 11:32:01 AM by Hibernate Tools 5.2.12.Final

import java.util.HashSet;
import java.util.Set;

/**
 * UserTable generated by hbm2java
 */
public class UserTable implements java.io.Serializable {

	private long userId;
	private String firstName;
	private Set<PhoneNumber> phoneNumbers = new HashSet<PhoneNumber>(0);

	public UserTable() {
	}

	public UserTable(long userId) {
		this.userId = userId;
	}

	public UserTable(long userId, String firstName, Set<PhoneNumber> phoneNumbers) {
		this.userId = userId;
		this.firstName = firstName;
		this.phoneNumbers = phoneNumbers;
	}

	public long getUserId() {
		return this.userId;
	}

	public void setUserId(long userId) {
		this.userId = userId;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public Set<PhoneNumber> getPhoneNumbers() {
		return this.phoneNumbers;
	}

	public void setPhoneNumbers(Set<PhoneNumber> phoneNumbers) {
		this.phoneNumbers = phoneNumbers;
	}

	@Override
	public String toString() {
		return "UserTable [userId=" + userId + ", firstName=" + firstName + ", phoneNumbers=" + phoneNumbers + "]";
	}

}
